const SEO_CITIES = {
  // --- 100 Top Indian Cities ---
  "mumbai": { name: "Mumbai", state: "Maharashtra", country: "India" },
  "delhi": { name: "New Delhi", state: "Delhi", country: "India" },
  "bangalore": { name: "Bangalore", state: "Karnataka", country: "India" },
  "hyderabad": { name: "Hyderabad", state: "Telangana", country: "India" },
  "ahmedabad": { name: "Ahmedabad", state: "Gujarat", country: "India" },
  "chennai": { name: "Chennai", state: "Tamil Nadu", country: "India" },
  "kolkata": { name: "Kolkata", state: "West Bengal", country: "India" },
  "surat": { name: "Surat", state: "Gujarat", country: "India" },
  "pune": { name: "Pune", state: "Maharashtra", country: "India" },
  "jaipur": { name: "Jaipur", state: "Rajasthan", country: "India" },
  "lucknow": { name: "Lucknow", state: "Uttar Pradesh", country: "India" },
  "kanpur": { name: "Kanpur", state: "Uttar Pradesh", country: "India" },
  "nagpur": { name: "Nagpur", state: "Maharashtra", country: "India" },
  "indore": { name: "Indore", state: "Madhya Pradesh", country: "India" },
  "thane": { name: "Thane", state: "Maharashtra", country: "India" },
  "bhopal": { name: "Bhopal", state: "Madhya Pradesh", country: "India" },
  "visakhapatnam": { name: "Visakhapatnam", state: "Andhra Pradesh", country: "India" },
  "patna": { name: "Patna", state: "Bihar", country: "India" },
  "vadodara": { name: "Vadodara", state: "Gujarat", country: "India" },
  "ghaziabad": { name: "Ghaziabad", state: "Uttar Pradesh", country: "India" },
  "ludhiana": { name: "Ludhiana", state: "Punjab", country: "India" },
  "agra": { name: "Agra", state: "Uttar Pradesh", country: "India" },
  "nashik": { name: "Nashik", state: "Maharashtra", country: "India" },
  "faridabad": { name: "Faridabad", state: "Haryana", country: "India" },
  "meerut": { name: "Meerut", state: "Uttar Pradesh", country: "India" },
  "rajkot": { name: "Rajkot", state: "Gujarat", country: "India" },
  "varanasi": { name: "Varanasi", state: "Uttar Pradesh", country: "India" },
  "srinagar": { name: "Srinagar", state: "J&K", country: "India" },
  "amritsar": { name: "Amritsar", state: "Punjab", country: "India" },
  "allahabad": { name: "Allahabad", state: "Uttar Pradesh", country: "India" },
  "ranchi": { name: "Ranchi", state: "Jharkhand", country: "India" },
  "guwahati": { name: "Guwahati", state: "Assam", country: "India" },
  "chandigarh": { name: "Chandigarh", state: "Chandigarh", country: "India" },
  "jodhpur": { name: "Jodhpur", state: "Rajasthan", country: "India" },
  "raipur": { name: "Raipur", state: "Chhattisgarh", country: "India" },
  "kota": { name: "Kota", state: "Rajasthan", country: "India" },
  "gwalior": { name: "Gwalior", state: "Madhya Pradesh", country: "India" },
  "dehradun": { name: "Dehradun", state: "Uttarakhand", country: "India" },
  "mysore": { name: "Mysore", state: "Karnataka", country: "India" },
  "bhubaneswar": { name: "Bhubaneswar", state: "Odisha", country: "India" },
  "gurgaon": { name: "Gurgaon", state: "Haryana", country: "India" },
  "noida": { name: "Noida", state: "Uttar Pradesh", country: "India" },
  "jalandhar": { name: "Jalandhar", state: "Punjab", country: "India" },
  "thiruvananthapuram": { name: "Thiruvananthapuram", state: "Kerala", country: "India" },
  "salem": { name: "Salem", state: "Tamil Nadu", country: "India" },
  "aligarh": { name: "Aligarh", state: "Uttar Pradesh", country: "India" },
  "bareilly": { name: "Bareilly", state: "Uttar Pradesh", country: "India" },
  "moradabad": { name: "Moradabad", state: "Uttar Pradesh", country: "India" },
  "bhiwandi": { name: "Bhiwandi", state: "Maharashtra", country: "India" },
  "jabalpur": { name: "Jabalpur", state: "Madhya Pradesh", country: "India" },
  "hubli": { name: "Hubli", state: "Karnataka", country: "India" },
  "madurai": { name: "Madurai", state: "Tamil Nadu", country: "India" },
  "trichy": { name: "Trichy", state: "Tamil Nadu", country: "India" },
  "coimbatore": { name: "Coimbatore", state: "Tamil Nadu", country: "India" },
  "vijayawada": { name: "Vijayawada", state: "Andhra Pradesh", country: "India" },
  "cuttack": { name: "Cuttack", state: "Odisha", country: "India" },
  "rourkela": { name: "Rourkela", state: "Odisha", country: "India" },
  "mangalore": { name: "Mangalore", state: "Karnataka", country: "India" },
  "belgaum": { name: "Belgaum", state: "Karnataka", country: "India" },
  "udaipur": { name: "Udaipur", state: "Rajasthan", country: "India" },
  "bikaner": { name: "Bikaner", state: "Rajasthan", country: "India" },
  "ajmer": { name: "Ajmer", state: "Rajasthan", country: "India" },
  "bhilwara": { name: "Bhilwara", state: "Rajasthan", country: "India" },
  "alwar": { name: "Alwar", state: "Rajasthan", country: "India" },
  "bharatpur": { name: "Bharatpur", state: "Rajasthan", country: "India" },
  "sikar": { name: "Sikar", state: "Rajasthan", country: "India" },
  "pali": { name: "Pali", state: "Rajasthan", country: "India" },
  "sri-ganganagar": { name: "Sri Ganganagar", state: "Rajasthan", country: "India" },
  "kochi": { name: "Kochi", state: "Kerala", country: "India" },
  "kozhikode": { name: "Kozhikode", state: "Kerala", country: "India" },
  "thrissur": { name: "Thrissur", state: "Kerala", country: "India" },
  "kannur": { name: "Kannur", state: "Kerala", country: "India" },
  "kollam": { name: "Kollam", state: "Kerala", country: "India" },
  "shimla": { name: "Shimla", state: "Himachal Pradesh", country: "India" },
  "jammu": { name: "Jammu", state: "J&K", country: "India" },
  "panipat": { name: "Panipat", state: "Haryana", country: "India" },
  "rohtak": { name: "Rohtak", state: "Haryana", country: "India" },
  "hisar": { name: "Hisar", state: "Haryana", country: "India" },
  "karnal": { name: "Karnal", state: "Haryana", country: "India" },
  "ambala": { name: "Ambala", state: "Haryana", country: "India" },
  "yamunanagar": { name: "Yamunanagar", state: "Haryana", country: "India" },
  "panchkula": { name: "Panchkula", state: "Haryana", country: "India" },
  "kurukshetra": { name: "Kurukshetra", state: "Haryana", country: "India" },
  "sirsa": { name: "Sirsa", state: "Haryana", country: "India" },
  "bhatinda": { name: "Bhatinda", state: "Punjab", country: "India" },
  "pathankot": { name: "Pathankot", state: "Punjab", country: "India" },
  "patiala": { name: "Patiala", state: "Punjab", country: "India" },
  "hoshiarpur": { name: "Hoshiarpur", state: "Punjab", country: "India" },
  "moga": { name: "Moga", state: "Punjab", country: "India" },
  "batala": { name: "Batala", state: "Punjab", country: "India" },
  "dhanbad": { name: "Dhanbad", state: "Jharkhand", country: "India" },
  "bokaro": { name: "Bokaro", state: "Jharkhand", country: "India" },
  "jamshedpur": { name: "Jamshedpur", state: "Jharkhand", country: "India" },
  "bhagalpur": { name: "Bhagalpur", state: "Bihar", country: "India" },
  "muzaffarpur": { name: "Muzaffarpur", state: "Bihar", country: "India" },
  "gaya": { name: "Gaya", state: "Bihar", country: "India" },
  "darbhanga": { name: "Darbhanga", state: "Bihar", country: "India" },
  "purnia": { name: "Purnia", state: "Bihar", country: "India" },
  "arrah": { name: "Arrah", state: "Bihar", country: "India" },
  "begusarai": { name: "Begusarai", state: "Bihar", country: "India" },

  // --- 100 Top Global Cities ---
  "london": { name: "London", state: "England", country: "UK" },
  "new-york": { name: "New York", state: "New York", country: "USA" },
  "tokyo": { name: "Tokyo", state: "Tokyo", country: "Japan" },
  "paris": { name: "Paris", state: "Ile-de-France", country: "France" },
  "dubai": { name: "Dubai", state: "Dubai", country: "UAE" },
  "singapore": { name: "Singapore", state: "", country: "Singapore" },
  "los-angeles": { name: "Los Angeles", state: "California", country: "USA" },
  "sydney": { name: "Sydney", state: "NSW", country: "Australia" },
  "toronto": { name: "Toronto", state: "Ontario", country: "Canada" },
  "berlin": { name: "Berlin", state: "Berlin", country: "Germany" },
  "rome": { name: "Rome", state: "Lazio", country: "Italy" },
  "madrid": { name: "Madrid", state: "Madrid", country: "Spain" },
  "amsterdam": { name: "Amsterdam", state: "North Holland", country: "Netherlands" },
  "moscow": { name: "Moscow", state: "Moscow", country: "Russia" },
  "vienna": { name: "Vienna", state: "Vienna", country: "Austria" },
  "istanbul": { name: "Istanbul", state: "Istanbul", country: "Turkey" },
  "beijing": { name: "Beijing", state: "Beijing", country: "China" },
  "shanghai": { name: "Shanghai", state: "Shanghai", country: "China" },
  "seoul": { name: "Seoul", state: "Seoul", country: "South Korea" },
  "bangkok": { name: "Bangkok", state: "Bangkok", country: "Thailand" },
  "hong-kong": { name: "Hong Kong", state: "", country: "Hong Kong" },
  "kuala-lumpur": { name: "Kuala Lumpur", state: "Kuala Lumpur", country: "Malaysia" },
  "manila": { name: "Manila", state: "Metro Manila", country: "Philippines" },
  "jakarta": { name: "Jakarta", state: "Jakarta", country: "Indonesia" },
  "taipei": { name: "Taipei", state: "Taipei", country: "Taiwan" },
  "osaka": { name: "Osaka", state: "Osaka", country: "Japan" },
  "melbourne": { name: "Melbourne", state: "Victoria", country: "Australia" },
  "auckland": { name: "Auckland", state: "Auckland", country: "New Zealand" },
  "brisbane": { name: "Brisbane", state: "Queensland", country: "Australia" },
  "perth": { name: "Perth", state: "Western Australia", country: "Australia" },
  "chicago": { name: "Chicago", state: "Illinois", country: "USA" },
  "houston": { name: "Houston", state: "Texas", country: "USA" },
  "miami": { name: "Miami", state: "Florida", country: "USA" },
  "atlanta": { name: "Atlanta", state: "Georgia", country: "USA" },
  "boston": { name: "Boston", state: "Massachusetts", country: "USA" },
  "san-francisco": { name: "San Francisco", state: "California", country: "USA" },
  "seattle": { name: "Seattle", state: "Washington", country: "USA" },
  "washington": { name: "Washington", state: "D.C.", country: "USA" },
  "denver": { name: "Denver", state: "Colorado", country: "USA" },
  "dallas": { name: "Dallas", state: "Texas", country: "USA" },
  "san-diego": { name: "San Diego", state: "California", country: "USA" },
  "las-vegas": { name: "Las Vegas", state: "Nevada", country: "USA" },
  "philadelphia": { name: "Philadelphia", state: "Pennsylvania", country: "USA" },
  "detroit": { name: "Detroit", state: "Michigan", country: "USA" },
  "phoenix": { name: "Phoenix", state: "Arizona", country: "USA" },
  "vancouver": { name: "Vancouver", state: "British Columbia", country: "Canada" },
  "montreal": { name: "Montreal", state: "Quebec", country: "Canada" },
  "calgary": { name: "Calgary", state: "Alberta", country: "Canada" },
  "ottawa": { name: "Ottawa", state: "Ontario", country: "Canada" },
  "edmonton": { name: "Edmonton", state: "Alberta", country: "Canada" },
  "mexico-city": { name: "Mexico City", state: "CDMX", country: "Mexico" },
  "sao-paulo": { name: "Sao Paulo", state: "Sao Paulo", country: "Brazil" },
  "rio-de-janeiro": { name: "Rio de Janeiro", state: "Rio de Janeiro", country: "Brazil" },
  "buenos-aires": { name: "Buenos Aires", state: "Buenos Aires", country: "Argentina" },
  "bogota": { name: "Bogota", state: "Bogota", country: "Colombia" },
  "lima": { name: "Lima", state: "Lima", country: "Peru" },
  "santiago": { name: "Santiago", state: "Santiago", country: "Chile" },
  "caracas": { name: "Caracas", state: "Capital District", country: "Venezuela" },
  "cape-town": { name: "Cape Town", state: "Western Cape", country: "South Africa" },
  "johannesburg": { name: "Johannesburg", state: "Gauteng", country: "South Africa" },
  "cairo": { name: "Cairo", state: "Cairo", country: "Egypt" },
  "nairobi": { name: "Nairobi", state: "Nairobi", country: "Kenya" },
  "lagos": { name: "Lagos", state: "Lagos", country: "Nigeria" },
  "casablanca": { name: "Casablanca", state: "Casablanca-Settat", country: "Morocco" },
  "accra": { name: "Accra", state: "Greater Accra", country: "Ghana" },
  "addis-ababa": { name: "Addis Ababa", state: "Addis Ababa", country: "Ethiopia" },
  "riyadh": { name: "Riyadh", state: "Riyadh", country: "Saudi Arabia" },
  "jeddah": { name: "Jeddah", state: "Makkah", country: "Saudi Arabia" },
  "mecca": { name: "Mecca", state: "Makkah", country: "Saudi Arabia" },
  "abu-dhabi": { name: "Abu Dhabi", state: "Abu Dhabi", country: "UAE" },
  "doha": { name: "Doha", state: "Doha", country: "Qatar" },
  "kuwait-city": { name: "Kuwait City", state: "Al Asimah", country: "Kuwait" },
  "tel-aviv": { name: "Tel Aviv", state: "Tel Aviv", country: "Israel" },
  "jerusalem": { name: "Jerusalem", state: "Jerusalem", country: "Israel" },
  "tehran": { name: "Tehran", state: "Tehran", country: "Iran" },
  "baghdad": { name: "Baghdad", state: "Baghdad", country: "Iraq" },
  "karachi": { name: "Karachi", state: "Sindh", country: "Pakistan" },
  "dhaka": { name: "Dhaka", state: "Dhaka", country: "Bangladesh" },
  "lahore": { name: "Lahore", state: "Punjab", country: "Pakistan" },
  "colombo": { name: "Colombo", state: "Western Province", country: "Sri Lanka" },
  "kathmandu": { name: "Kathmandu", state: "Bagmati", country: "Nepal" },
  "yangon": { name: "Yangon", state: "Yangon Region", country: "Myanmar" },
  "ho-chi-minh-city": { name: "Ho Chi Minh City", state: "HCMC", country: "Vietnam" },
  "hanoi": { name: "Hanoi", state: "Hanoi", country: "Vietnam" },
  "oslo": { name: "Oslo", state: "Oslo", country: "Norway" },
  "stockholm": { name: "Stockholm", state: "Stockholm", country: "Sweden" },
  "copenhagen": { name: "Copenhagen", state: "Capital Region", country: "Denmark" },
  "helsinki": { name: "Helsinki", state: "Uusimaa", country: "Finland" },
  "warsaw": { name: "Warsaw", state: "Masovia", country: "Poland" },
  "prague": { name: "Prague", state: "Prague", country: "Czechia" },
  "budapest": { name: "Budapest", state: "Central Hungary", country: "Hungary" },
  "bucharest": { name: "Bucharest", state: "Bucharest", country: "Romania" },
  "athens": { name: "Athens", state: "Attica", country: "Greece" },
  "dublin": { name: "Dublin", state: "Leinster", country: "Ireland" },
  "lisbon": { name: "Lisbon", state: "Lisbon", country: "Portugal" },
  "brussels": { name: "Brussels", state: "Brussels", country: "Belgium" },
  "geneva": { name: "Geneva", state: "Geneva", country: "Switzerland" },
  "zurich": { name: "Zurich", state: "Zurich", country: "Switzerland" },
  "wellington": { name: "Wellington", state: "Wellington", country: "New Zealand" },
  "fiji": { name: "Suva", state: "Central Division", country: "Fiji" }
};

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const match = url.pathname.match(/^\/weather\/([a-z0-9-]+)\/?$/);
    
    if (match) {
      const slug = match[1];
      const cityData = SEO_CITIES[slug];
      
      const response = await env.ASSETS.fetch(new Request(new URL('/', request.url), request));
      
      if (cityData && response.status === 200) {
        const stateText = cityData.state ? `${cityData.state}, ` : "";
        const fullLocation = `${cityData.name}, ${stateText}${cityData.country}`;
        
        const seoTitle = `${fullLocation} Weather Forecast | World Weather Hub`;
        const seoDesc = `Get accurate real-time local weather conditions, hourly forecasts, and 16-day weather forecast for ${fullLocation}.`;
        const canonicalUrl = `https://${url.hostname}/weather/${slug}/`;

        return new HTMLRewriter()
          .on('title', { element(e) { e.setInnerContent(seoTitle); } })
          .on('meta[name="description"]', { element(e) { e.setAttribute('content', seoDesc); } })
          .on('link[rel="canonical"]', { element(e) { e.setAttribute('href', canonicalUrl); } })
          .on('h1', { element(e) { e.setInnerContent(`${fullLocation} Local Weather Forecast & Conditions`); } })
          .transform(response);
      }
      return response;
    }
    
    return env.ASSETS.fetch(request);
  }
};
